image: atlassian/pipelines-awscli
pipelines:
 custom:
   deploy-automation-testing:
     - step:
         script:
           - apk update
           - apk add zip
           - mkdir zipped
           - zip -r ./zipped/testing-automation.zip . -x *.git* --exclude=*.DS_Store*
           - aws s3 --region "ap-south-1" sync ./zipped/ s3://fundsindiacodebuildbucket/